### ISSUE TITLE
doc add explanation of the output

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#100]
- [ ] general explanation
- [ ] difference between warnings and errors

**Comment by rrd108** [comment]
@Whomy09 Are you open to add these?

**Comment by Whomy09** [comment]
@rrd108 Yes of course, but it is not clear to me what I should do 😅

**Comment by rrd108** [comment]
Ah wonderful.

There is an example output image at the root. You can add it to the docs and explain what the user see and what they should do about it.

Like the first line shows what rulesets are applied, then you see what problems the tool found, where they find the explanation in the docs, and all output suggest a solution.

Then explain that yellow messages are soft warnings what are advisable to follow and red ones are the ones to really fix.

**Comment by Whomy09** [comment]
@rrd108 I will wait for #64 to finish because the output structure will change

**Comment by David-Pena** [comment]
Hi @Whomy09 the output layout is basically confirmed in #64 

If you want, you can work with the images in this comment https://github.com/rrd108/vue-mess-detector/issues/64#issuecomment-2274055287 (screenshots for both groupBy option, per rule or file)

**Comment by Whomy09** [comment]
@David-Pena Excellent, I will be working on this

**Comment by David-Pena** [comment]
I like the content and structure of the explanation, I noticed a few wordings that might be a bit confusing, check it out this markdown with a few changes in the wordings, and let me know what do you think? @Whomy09 

⬇️

**Group by Rule:** In this view, the first line is highlighted in blue, representing the rule being evaluated. Following this, you'll see blocks of information structured as follows: file path, description, and message.

**Group by File:** In this view, the first line displays the file path being evaluated. Below this, you'll see blocks of information with the following structure: rule, description, and message.

- **Rule:** The blue line that defines the specific rule being evaluated.
- **File:** Shows the path to the file where the rule is applied.
- **Description:** A concise explanation of the rule, often accompanied by a link to relevant documentation for further details.
- **Message:** Indicates the line of code where the rule was violated. Yellow messages are warnings, suggesting best practices, while red messages highlight errors that must be corrected.

⬆️

**Comment by David-Pena** [comment]
Also, this issue was about adding the output explanation to the docs, not to the README
