### ISSUE TITLE
add rule (rrd) nested ternary

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#112]
Ternary should be simple and short

**Comment by David-Pena** [comment]
Simple and short means just one level? 

For example:
```js
const value = isValid ? something : somethingElse 
```

Or would this be simple too?
```js
const value = isValid ? something : anotherCondition ? somethingElse : "🫡"
```

Sorry for the messy example

**Comment by rrd108** [comment]
- [ ] no nesting
- [ ] simple logic

The following example is not nested but not simple at all

```ts
const isSimple = num < 10 && str != 'rrd' || day > wednesday ? true : false
```

Rethinking it maybe this is a different rule as the same condition would be confusing in an `if` not just in a ternary 

Maybe this rule should check only nesting?

**Comment by David-Pena** [comment]
> Maybe this rule should check only nesting?

Yes, I agree.

So for the `if` do we have a rule for that already?

**Comment by rrd108** [comment]
No, we do not have a rule yet for complicated conditions
