### ISSUE TITLE
`functionSize` check is extremely slow

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#119]
**Describe the bug**
When we run `yarn analyze` with the `functionSize` check for certain vue files it become extremely slow (5s) and could cause total freezing #116 

**To Reproduce**
Run `yarn analyze` on a codebase what contains this file: https://github.com/rrd108/sadhana/blob/main/src/components/SettingsNotifications.vue
Currently the arrow function check is commented out, so you should uncomment, and build before you run analyze.

**Expected behavior**
All checks should run under 1 sec

**Additional context**
The issue is somehow connected the arrow function regex. I hope @David-Pena you can find out why it happens and how to fix it.

**Comment by David-Pena** [comment]
I tried to optimize by combining the regex and doing just one general loop but didnt achieve any progress... it was taking 8000ms with the codebase you provided.

Maybe we can research about tools like [neotraverse](https://github.com/PuruVJ/neotraverse) or something that can help us to handle more efficiently the functions matches. I'm just thinking out loud so any feedback is welcome @rrd108

**Comment by rrd108** [comment]
Did you tried a non regex solution?

Something like here https://github.com/rrd108/vue-mess-detector/blob/main/docs/checkMissing.js#L58

**Comment by David-Pena** [comment]
Not really.

I'll try without regex tomorrow morning 🫡

**Comment by David-Pena** [comment]
A non regex solution is what we need it. I'm trying a few things and for now its working quite good.

![image](https://github.com/user-attachments/assets/64224c2a-8111-4a85-9664-236654753833)

The file you provided `SettingsNotifications` is the `0.229ms`

Now I'm going to add some tests for arrow functions without curly braces.. and refactor the code a little bit

**Comment by David-Pena** [comment]
actually, if a function doesnt have curly braces, it can only be one line deep, right? @rrd108 I just remember seeing a comment from you about this

**Comment by rrd108** [comment]
Arrow functions without curly braces can be multiple lines 

```
  const getOpenBookings = (page: number) =>
    axios
      .get(`${import.meta.env.VITE_APP_API_URL}bookings/listOpen.json?page=${page}`, store.tokenHeader)
      .then(res => {
        bookings.value = res.data.bookings
        paginate.value = res.data.paginate
      })
      .catch(err => console.error(err))
```

**Comment by David-Pena** [comment]
Ohh right, as long its from the same context it can have multiple lines, got it. I'll add a few test for that
