### ISSUE TITLE
add rule (rrd): prop drilling

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#12]

**Comment by David-Pena** [comment]
@rrd108 I think a brief description is missing for this issue, what do you have in mind?

**Comment by rrd108** [comment]
Props drilling is when you give some `props` to a component but the component itself never use them, it just forwards them to one (or more) of its children.

The reccomended solution is move out the drilled `prop` to a store, or use `provide` - `inject`, etc.

**Comment by David-Pena** [comment]
So one possible solution could be ⬇️
1. Extract props
2. Check if one prop only appears as attribute / prop of another tag in the `<template>`
3. If it does, log ouput...

**Comment by rrd108** [comment]
Yes.

I mean if the child component get it unmodifed. So for example if the prop is `products` but the child component gets `products.filter(...)` then it should not be reported.
