### ISSUE TITLE
add a script to check if a new rule is added properly

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#126]

**Comment by David-Pena** [comment]
Awesome feat!

**Comment by rrd108** [comment]
We had to have something like this. A few rules were already missing here and there.

I was not have time yet to fix them all.

**Comment by David-Pena** [comment]
I just ran the command and I see whats missing, if you are not on it I'll add those

**Comment by rrd108** [comment]
I already off my computer, so go ahead if you want 🤩

**Comment by David-Pena** [comment]
Commits added in #128 as they were minor
