### ISSUE TITLE
Add code health measure to output 

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#130]
@David-Pena what do you think calculating a code health?

Something like all warnings collected by the analyzer divided by the number of lines of all vue files?

Or something similiar but defendable ratio?

Maybe some scientific measure already exists..

**Comment by David-Pena** [comment]
Interesting..

Something like number of offenses per file divided by the number of files? There can be a ratio here

**Comment by rrd108** [comment]
I like that also.

Or the number of rule violations per 1000 lines of code?

**Comment by David-Pena** [comment]
We need to do a sample implementation using one of those formulas and try it again a different codebases and check which formula is better

**Comment by rrd108** [comment]
Nice idea.

Non of the implementations is difficult, so we can do them and check what numbers we get.

I have quite a few project to test on.

I am off computer till Tuesday, we organize a wedding on Monday.

**Comment by David-Pena** [comment]
Got it.

If I code today, I'll do this first and we can decide

Good luck with the wedding planning 🫡

**Comment by rrd108** [comment]
You take whatever issue you want. We have quite a few and I am ok with any of them.

Just assign it to yourself so we do not step on each other toes.

**Comment by rrd108** [comment]
Just to clarify.

It should be calculated only on the applied rules, skipping the ignored ones.

**Comment by rrd108** [comment]
@David-Pena what doyou think about this one?

**Comment by rrd108** [comment]
I just fixed the calculation. 

I was suprised why I get so low scores for my vue projects... And the calculation was wrong. Now they are in the `OK` zone - what sounds much realistic.

**Comment by David-Pena** [comment]
@rrd108 , I would lean towards the first approach (errors per lines of code) as it provides a more detailed and size-aware measure of code health.

Also mine was giving me super low values and comparing both approaches, yours is better.

I think we should improve the first approach in the future to assign differents weights to some rules, because the warning/error levels should affect this score.

**Comment by rrd108** [comment]
Ok.

What about using a weight to these? Like 1 for warnings at 1.5 to errors?

**Comment by David-Pena** [comment]
> What about using a weight to these? Like 1 for warnings at 1.5 to errors?

Let's try it and we will decide
