### ISSUE TITLE
`analyze` is not entering subdirectories, only grabs vue files from the root of the given path

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#134]
**Describe the bug**
When running the analyzer in a folder where subdirectories are present, it ignores the subdirectories and only analyze the vue files from the root.

**To Reproduce**
Run the analyzer to a path like this (a vue file plus subdirectories which contains more vue files)
![image](https://github.com/user-attachments/assets/1b603056-1c1c-4766-b24b-f425dff52d14)

And you will see that only one file was analyzed
![image](https://github.com/user-attachments/assets/a516b2f9-1746-41f6-addb-6797ea2200aa)

1. What is the exact code you are analyzing?
The issue might be in the traversal changes from last release.
3. What is the output you are getting?
Only one file is being analyzed

**Expected behavior**
All files from each subdirectory should be analyzed too

**Screenshots**
⬆️

**Used version number of vue-mess-detector:**
`v0.29.0`

**Used version number of node & yarn:**
`node v20.15.0`
`yarn v1.22.21`

**Additional context**
> Subdirectories in pages can be a problem. I changed the directory traversal recently
@rrd108 We'd appreciate your help here

**Comment by David-Pena** [comment]
Is this solved in the latest release? @rrd108 

I just run it on the same file structure and its only analyzing the `vue` file at the root

**Comment by rrd108** [comment]
I om in. Something does not work as expected

**Comment by rrd108** [comment]
when I run it via yarn or node (from bin) all is fine. But npx errors out for some reason.

**Comment by rrd108** [comment]
Please check if 0.31.0 solve this on windows.

On Linux it works fine

**Comment by David-Pena** [comment]
It worked! `npx vue-mess-detector analyze path` works on windows 🚀

I saw you added like a comment at the top of some files, was that the solution?

**Comment by rrd108** [comment]
Kindof... I added a shebang what may cause problems on Windows, we wil see :smile:

**Comment by David-Pena** [comment]
> Kindof... I added a shebang what may cause problems on Windows, we wil see 😄

The shebang is actually a human-readable instance of a `magic-number` in the executable file...

Offending your own rules huh? haha
