### ISSUE TITLE
Add support to analyze composables, utilities etc

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#137]
As we suggest in some rules to move out some of the code from components, we should support analyze not only vue files but js/ts files also.

Some of the rules should be ignored and some of them might need some tweak.

**Comment by David-Pena** [comment]
Should this be by default or if a specific flag is entered?

With the latter, we can just check for that flag and apply a few rules

**Comment by rrd108** [comment]
What do you think?

I would do it by default

**Comment by David-Pena** [comment]
I vote for default

**Comment by rrd108** [comment]
For this we have to have a list of rules what can be aplied for non vue files to avoid false warnings.

Should we put it to the `src/rules/rules.ts` file? How?

**Comment by David-Pena** [comment]
Should we treat it as new ruleset you mean?

**Comment by David-Pena** [comment]
Ohh I see, I like that approach! It's more scalable.

Here are my suggestions for the `onlyVue` bool
- strictlyVue
- limitToVue
- vueTargeted

My brain is limited this morning so those are my suggestions for now

**Comment by rrd108** [comment]
Might we have rules only for certain types of files?

If yes maybe the third property can be an array 

```ts
apply: [vue, js,ts]
```

Or might we have specific rules for example for the server directory's files?

If yes we need handle that.

**Comment by David-Pena** [comment]
> Might we have rules only for certain types of files?

I mean I thought about it but our only scenarios are vue files or js/ts files right? or when you say `directory's files` what do you mean?

**Comment by rrd108** [comment]
Yes, only vue and ts/js files.

**Comment by rrd108** [comment]
I meant by directory's files that we may have particular rules what applies only for files in composables or in api directories.

I have nothing in my mind right now, but I can imagine to have something.

For example differenciate composables and utilities and warn if a utility is in the composables folder.

Maybe we can decide later as if we move to the new rules array form it becomes extensible, we can add new properties if needed.

Perhaps I am just thinking loudly.

**Comment by David-Pena** [comment]
> Maybe we can decide later as if we move to the new rules array form it becomes extensible, we can add new properties if needed.

I think we might add new rules at some point for this escenario, there are a lot of content about how to write a good composable that can help us to think of rules.

Now for our current set of rules, I see multiple of then applying also to just `js/ts` files. For example:
- all `rrd` rules except `tooManyProps, propsDrilling...` (your ruleset has the most rules that can be apply for both escenarios
- some of the `vue-strong` like `simpleComputed`

So yes, let's revisit this later after the refactor of the rules array.

**Comment by rrd108** [comment]
`rulesCheck.ts` calls all the check functions. We can do a check here if `filePath.endsWith('.ts')` and do not even enter the check if it is not needed for `ts`/`js` files.

Or we can do the same check inside the rules themselves.

I would prefer the first as it keeps the rules simpler.

**Comment by rrd108** [comment]
Rethinking it I think rules what gets the `script` as their first param are the ones what should be checked for `ts`/`js` files and those what gets `template`, or `styles` are not.

so mabe we do not need to reformat the RULES object

**Comment by rrd108** [comment]
@David-Pena can you check it? [139-generate-skeleton-for-new-rules branch](https://github.com/rrd108/vue-mess-detector/tree/139-generate-skeleton-for-new-rules)

**Comment by David-Pena** [comment]
> Rethinking it I think rules what gets the script as their first param are the ones what should be checked for ts/js files and those what gets template, or styles are not.

Nice catch! 

I just tried with some composable folders and utils js/ts files and it worked fine!

**Comment by rrd108** [comment]
I guess it is almost done, needs some tweaking.

checkRules became a little more complicated. Are you ok with that?

Otherwise we can add specific rules now, targeting nitro, composables, etc.

**Comment by David-Pena** [comment]
> checkRules became a little more complicated. Are you ok with that?

Yes, it was confusing a the beginning but because I misread your comment.

I think we need to add something to indicate when the rule should be for js/ts or for vue only. I'm not sure if as a comment in the `rulesCheck` file or in new issues we create a label for it.  What do you think?

**Comment by rrd108** [comment]
I think a comment is better. And perhaps a sentence in the contributors guide

**Comment by David-Pena** [comment]
> I think a comment is better. And perhaps a sentence in the contributors guide

Good 🫡
