### ISSUE TITLE
generate skeleton for new rules

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#139]
- [x] generate rule file skeleton
- [x] geberate test fiel skeleton

@David-Pena I was thinking about helping other developers (and ourselves) generating new rules.

Can you please try it and share your thoughts?

At the moment you can try it by `node ./src/generator/createRule.js `

**Comment by David-Pena** [comment]
Oh so `inquirir` is how you can prompt things to the user. I'm learning so much with this project 🔥

This feature is awesome!

What if we add more to it, for example not just creating the rule files, but what if we add by default the rule's name to `rules/rules.ts` and `rulesCheck, rulesReport`.

What do you think?

**Comment by rrd108** [comment]
> What if we add more to it, for example not just creating the rule files, but what if we add by default the rule's name to `rules/rules.ts` and `rulesCheck, rulesReport`.

Yes, it should be like that. 

I am not satisfied with the skeleton yet.

1. I would like to add the line number to the output also. It would be nice to have it everywhere possible, so I think the skeleton should contain it.
2. Somehow I want to mark more clearly what to change in the generated files.

**Comment by David-Pena** [comment]
> Yes, it should be like that.

Awesome 🚀

> I would like to add the line number to the output also. It would be nice to have it everywhere possible, so I think the skeleton should contain it

The `lineNumber` was something I struggled with my first issue in this project so I agree with you, it should be there.

> Somehow I want to mark more clearly what to change in the generated files.

What about snippets behavior? you know you can set up the snippet in a way that you can set where the cursor should be and if it should select by default a line or something. 

I'm not sure how this ⬆️ is done but some research would do it

**Comment by rrd108** [comment]
Creating snippet will be a vscode only addition. 

Personally I do not like them.

What about adding comments explaining what to do at the lines where we (they) should put actual code?

**Comment by David-Pena** [comment]
> What about adding comments explaining what to do at the lines where we (they) should put actual code?

I thought you didnt like comments for this, in that case yes, comments would be the most appropiate.

This is how you see it?
```js
const checkThisIsATest = (script: SFCScriptBlock | null, filePath: string) => {
  // TODO: Check if the `script` is null
  if (!script) {
    return
  }

  // TODO: Create regex to match the pattern for this rule
  const regex = createRegExp()
  const matches = script.content.match(regex)

  // TODO: Push to `results` array if matches are found
  if (matches?.length) {
    results.push({ 
      filePath, 
      message: `add_your_message ${BG_ERR}(${matches.length})${BG_RESET}`
    })
  }
}

or you mean no code at all, just comments explaining and giving context of what to do?
```

**Comment by rrd108** [comment]
Ah yeah I like this approach adding TODO comments.
Simple, clear, easy to understand and follow.

Tomorrow I will update the skeleton. If nobody does it earlier 😉

**Comment by David-Pena** [comment]
> Tomorrow I will update the skeleton. If nobody does it earlier 😉

haha I have one issue assigned already 👀

**Comment by rrd108** [comment]
Can you check and tell me what do you think? It is in [139-generate-skeleton-for-new-rules branch](https://github.com/rrd108/vue-mess-detector/tree/139-generate-skeleton-for-new-rules)

**Comment by David-Pena** [comment]
I see one typo:
![image](https://github.com/user-attachments/assets/0ca26ae3-9267-4ff5-95cf-0239da0b8cc6)
- `follwoing` > `following` (newRuleFile)

And also, in both files the `rule` field must be ``${TEXT_INFO}RULESET ~ RULENAME${TEXT_RESET}`, where:
- `RULESET` we know what it is
- `RULENAME` should be the name of the file (name of the rule) but splitted, in this case the rule is called `complicatedConditions`, then the rulename for the offense object should be `complicated conditions`

Result ⬇️
```js
results.forEach((result) => {
      offenses.push({
        file: result.filePath,
        rule: `${TEXT_INFO}rrd ~ complicated conditions${TEXT_RESET}`,
        description: `👉 ${TEXT_WARN}/* TODO tip to fix this issue */.${TEXT_RESET} See: https:///* TODO doc link */`,
        message: `${result.message} 🚨`,
      })
})
```

```js
expect(reportComplicatedConditions()).toStrictEqual([{
      file: fileName,
      rule: `${TEXT_INFO}rrd ~ complicated conditions${TEXT_RESET}`,
      description: `👉 ${TEXT_WARN}/* TODO tip to fix this issue */.${TEXT_RESET} See: https:///* TODO doc link */`,
      message: `line #/* TODO line number from your content above*/ ${BG_WARN}/* TODO message from the rule file */${BG_RESET} 🚨`,
    }])
```

**Comment by rrd108** [comment]
Does it mean you like it in general?

**Comment by rrd108** [comment]
Ah I see you answered that also.

Thanks I will fix it and merge it

**Comment by David-Pena** [comment]
> Does it mean you like it in general?

Yes 🔥 I edited the order of my comment haha

**Comment by rrd108** [comment]
implemented in https://github.com/rrd108/vue-mess-detector/releases/tag/v0.32.0
