### ISSUE TITLE
Add cli option to `order` results in output

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#140]
Details mentioned in https://github.com/rrd108/vue-mess-detector/issues/5#issuecomment-2236180626

**Comment by David-Pena** [comment]
I created a PR for this #148

**Comment by rrd108** [comment]
Now `asc` is the default. Was it intentional? I think `desc` is more logical to be the default - start with the most problematic.

**Comment by David-Pena** [comment]
It was intentional, I thought that was our final decision. I'll push a commit changing char

**Comment by rrd108** [comment]
Ah I see.

Ok, I still prefer `desc` order.

**Comment by David-Pena** [comment]
Updated in latest commit to main https://github.com/rrd108/vue-mess-detector/commit/5fc8fec084999235a3fbf433259ac3e79c9abd3b
