### ISSUE TITLE
add rule (rrd) props destructed

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#143]
```js
import { ref } from 'vue';

const { firstName, lastName } = defineProps({
  firstName: String,
  lastName: String,
});
```

Destructing props break reactivity.

**Comment by rrd108** [comment]
Daniel is trying this one

**Comment by David-Pena** [comment]
Cool! Welcome @Daniel 🫡

**Comment by rrd108** [comment]
:smile:  He is another Daniel

**Comment by David-Pena** [comment]
> :smile:  He is another Daniel

I don't know what you mean .. 👀

**Comment by rrd108** [comment]
A user named Daniel was marked in your previous comment.

**Comment by sagi-daniel** [comment]
> Cool! Welcome Daniel 🫡

Hi Hi, Nice to meet you! I m on. soon it wil be done
