### ISSUE TITLE
Single-word prop names fail the Prop Name Casing rule

### ISSUE THREAD

**Issue by zkriszti** [rrd108/vue-mess-detector#146]
**Describe the bug**
Single-word prop names fail the "Prop Name Casing" rule check (no matter whether they start with a lowercase or uppercase letter). 

**To Reproduce**
- [Link to repro](https://stackblitz.com/edit/vitejs-vite-lzj7ub?file=src%2Fcomponents%2FHelloWorld.vue)
- check the two components: they have single-word prop names (one starts lowercase, other one uppercase)
- start analysis from terminal: `npx vue-mess-detector analyze ./src/components`
- result will state that prop(s) should be renamed in both files: `Message: prop names are not camelCased 🚨`

**Expected behavior**
[MDN considers lowercased single words as camelCased words](https://developer.mozilla.org/en-US/docs/Glossary/Camel_case), so the rule shouldn't signal an error. (Probably the uppercased one shouldn't trigger an error either, but the lowercased one should definitely be accepted).

**Used version number of vue-mess-detector:**
0.34.0

**Used version number of node & yarn:**
node: 18.20.3 / npm: 10.2.3 / yarn: not applicable

**Additional context**
Thank you for this nice library! 🤩

**Comment by David-Pena** [comment]
HI @zkriszti 

Thanks for using this tool and opening an issue.

From the reproduction and context you gave, It's almost 100% clear the error is in identifying single lowercased words as valid. For the uppercase example we can discuss it later.

I'm going to give it a try to solve this issue

**Comment by David-Pena** [comment]
I just create a PR with the fix for this issue, all tests passing (I included the two you had in the repro link and more).

The releases are handled by @rrd108. Tomorrow morning I'm pretty sure there will be a release with this fix 🙌

Let me know if you have any questions

**Comment by rrd108** [comment]
implemented in v0.35.0
