### ISSUE TITLE
generate skeleton docs for new rules

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#149]
Being the base structure the following ⬇️⬇️

# Rule Name

Checks if ....

## ❓ Why it's good to follow this rule?

Content here...

## 😱 Examples of code for which this rule will throw a warning

Example of bad code...

Extra details of the example... (if applicable)

## 🤩 How to fix it?

Example of how to fix it 

Extra details of the example... (if applicable)

@rrd108 what do you think?

**Comment by rrd108** [comment]
That would be awesome, but in this case we have to update the docs checker to make sure the developer actually added some real documentation.

Maybe this can be generated with a separated command.

Generating the docs would be very helpful.

But we need to check if they added some real content.

In the same time I want to accept PRs without documentation. Some developers does not want to deal with it.

What do you think David?

**Comment by David-Pena** [comment]
> In the same time I want to accept PRs without documentation. Some developers does not want to deal with it.

I didn't think about this. You are right, maybe it can be a separate command so its not mandatory for new contributors. (And doesn't require any changes to the rules checker command)

But we definitely should have it, it would be super useful for us and anyone like us who like to add all content needed for a new rule 👏🏻

**Comment by David-Pena** [comment]
I'd like to try this one

**Comment by David-Pena** [comment]
I created a PR for this #171
