### ISSUE TITLE
handle long outputs

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#154]
When I analyze a bigger codebase and it has a lot of warnings and errors I can not scroll back to the top of the output, so I loose some of that.

If I redirect the output to a file it is hard to read because of the ascii characters.

**Comment by David-Pena** [comment]
Thinking...

**Comment by rrd108** [comment]
We can add a new cli flag to output to a file as csv or something.

But I have no idea for the console output

**Comment by rrd108** [comment]
Perhaps the output can be md, HTML, json or anything

**Comment by rrd108** [comment]
We can add a --condensed flag to output only the filename and number of errors 

BTW changing the scan directory will end up smaller output 

Maybe add a new flag to filter for filename patterns?

**Comment by David-Pena** [comment]
What if before the the main `Object.keys...` we check for the offenses array length and if it's greater than CONSOLE_DEFAULT_MAX_LINES we output just the condensed version you mentioned `(filename : number of offenses : rules offended)` And if this lower, we output as we usually do

The question would be how we define this CONSOLE_DEFAULT_MAX_LINES? Does it exist a number of lines where the output starts to crop itself? Do we make up one by try and error?

**Comment by David-Pena** [comment]
The math would be the 'offenses.length * 4" because we know for sure that per `offense` o next there are at least four lines being log in the output

**Comment by rrd108** [comment]
On my system the terminal holds 1,000 lines of output.

On a bigger project I have 13,000 lines of output

**Comment by David-Pena** [comment]
Then it varies a lot. My approach is not an option

**Comment by rrd108** [comment]
I was playing around with the output to have it more condensed and clear for long outputs.

![Képernyőkép 2024-08-29 18-29-15](https://github.com/user-attachments/assets/93faa28b-35c6-4166-83c4-43b952cc0f6b)

This would be the output if the user uses the `--output=table` flag

I think it looks more organized then our default one, but currently has some problems what is solved in the current `text` output.

On the other hand it does not solve the long output problem. I tried on a test project with 3 files and a middle sized project with 202 files.

| files | text output lines | table output lines |
| ------: | ------: | ------: |
|3 | 82 | 90 |
|202 | 8,233 | 6,366 |

So the output saves 23% in the number of lines of the output, but **far away** from what fits to the console. So it does not really serves the goal of shorting the output.

@David-Pena what do you think?

- Should we keep this output and solve the issues coming with it?
- Should we use this as the default output instead of `text`?
- Should we have a `plainText` output what can be used to redirected into a file, what does not contain the ascee escape characters, so it is more readable?
- Should we have a `plainTable` output for the same reason?
- For this I had to change the output object and I think it would server better our `json` output. So we could keep that even if we do not keep this output.

If you want to check out the code it is here: https://github.com/rrd108/vue-mess-detector/tree/table-output

**Comment by David-Pena** [comment]
> but currently has some problems what is solved in the current text output.

What problems?

> Should we have a plainText output what can be used to redirected into a file, what does not contain the ascee escape characters, so it is more readable?
> Should we have a plainTable output for the same reason?

I don’t get the goal of a plainText/plainTable output ⬆️

**Comment by rrd108** [comment]
> What problems?

Group by file not ready yet and text output is ruined

> I don’t get the goal of a plainText/plainTable output ⬆️

If you run 

```
yarn analyze > output.txt
```

The file will be hardly readable now because of the ascii codes.

**Comment by David-Pena** [comment]
I think the default one should be `text` as its our most stable one...
Let's keep the `--output=table` and add issues to fix the bugs to have at the same level of the default `text` option
For the export as a file option, I think it only makes sense to have it for the `table` output

> The file will be hardly readable now because of the ascii codes.

Lets create a helper function to remove all ASCII codes to be used when needed 💡

**Comment by rrd108** [comment]
Thanks. 
I will continue the work on table output.

**Comment by rrd108** [comment]
I think now with the new file output this is solved.

Long output in console still unsolved but by my understanding it is something what we can not really solve.
