### ISSUE TITLE
read cli options from a config file

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#161]
Is it possible to specify the rules to apply (or ignore) into a config file also?
This is useful when it comes to sharing the same standards across a team.

cli arguments are good, but keeping them in a config file means consistency!

Ty for this software, this is a good linter :)

We discussed about it here: https://x.com/radharadhya/status/1825913771413426300

_Originally posted by @FauconFan in https://github.com/rrd108/vue-mess-detector/issues/63#issuecomment-2299130456_

**Comment by rrd108** [comment]
@FauconFan minimum implementation is ready, we should add some error handling and validation and it is ready to be published. Keep you eye on it :smile:

**Comment by David-Pena** [comment]
That was quick 🚀

**Comment by rrd108** [comment]
> That was quick 🚀

I was sitting in a car whole day, I had some code withrawal effect when this is issue poped up :smiley:

**Comment by rrd108** [comment]
`json` seems to be an easier to support and implement config file format.

Refactor the current implementation
