### ISSUE TITLE
add rule (rrd) `toRefs()` 

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#162]
> Originally from: https://github.com/rrd108/vue-mess-detector/pull/158#issuecomment-2299287031

What would be the rule? @rrd108 

To not use props.PROPNAME but to use `toRefs` ?

**Comment by rrd108** [comment]
No, it is more complicated.

I will get back to this later.

**Comment by David-Pena** [comment]
Pending description @rrd108

**Comment by rrd108** [comment]
same as #220
