### ISSUE TITLE
doc add explanation of good first issue 

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#164]
I think we should add a sentence to the contributors guide docs explaining issues labeled as good first issue are marked for new contributors to jump in.

It also means we have to wait some time (for example a week) before we would assign ourselves to one of them.

@David-Pena what do you think?

**Comment by David-Pena** [comment]
Something like this?
![image](https://github.com/user-attachments/assets/e99432f9-8dc2-4b55-a840-44356fbfcd67)

**Comment by rrd108** [comment]
Yesss

**Comment by David-Pena** [comment]
Added in https://github.com/rrd108/vue-mess-detector/commit/e79cf3bcd8ec97ef6e52add372f0221da6f4a2ef
