### ISSUE TITLE
Exclude .output folder from scanning 

### ISSUE THREAD

**Issue by ManUtopiK** [rrd108/vue-mess-detector#166]
**Describe the bug**
Ignore chosen folder to analyse.

**To Reproduce**

1. What is the exact code you are analyzing?
Install nuxt, build it. There is now a `.output` folder (the build with minified files).
Running `npx vue-mess-detector analyze` will scan this `.output` folder.

2. What is the feature I want?

- Exclude this `.output` folder by default.
- A way to exclude/ignore folders/files to be analysed.

**Comment by David-Pena** [comment]
Hi @ManUtopiK 

I think this might be a feature, not a bug. Correct me if I'm wrong:
- You want to be able to exclude some file/folders to be analyzed in the given path, something like with a --exclude=patterns, right?

If thats the case that would be a feature, if not, please let me know more details to be able to help you 🙌

**Comment by rrd108** [comment]
Ah right, we missed it.

I can fix it tomorrow. Perhaps you can send a PR if you want.

**Comment by ManUtopiK** [comment]
@David-Pena Sorry, I started as a bug to notice to exclude the `.output` folder and added the idea to exclude folders/files...

**Comment by rrd108** [comment]
Folders and files are in #169
