### ISSUE TITLE
Fine-grained rules 

### ISSUE THREAD

**Issue by ManUtopiK** [rrd108/vue-mess-detector#167]
How to set the rules ?

I saw that we can exclude a set of rules with `--ignore=rrd`, but how to exclude one rule, like [`function-size`](https://vue-mess-detector.webmania.cc/rules/rrd/function-size.html) or how to set this rule to 30 lines of code.

Thanks for your module, it's amazing !

**Comment by David-Pena** [comment]
Hi @ManUtopiK 

First, welcome and thank you for using this tool 🙌

> I saw that we can exclude a set of rules with --ignore=rrd, but how to exclude one rule, like [function-size](https://vue-mess-detector.webmania.cc/rules/rrd/function-size.html)

Right now you can only ignore/apply rulesets (rrd, vue-essential, vue-strong, vue-recommended, vue-caution).
However, its within our scope to add this ignore/apply option to specific rules also #63 
@rrd108 is working on that one, but feel free to ask in the issue's details in case you want to contribute 🚀

> or how to set this rule to 30 lines of code.

This can be a new feature requiring further discussion @rrd108

**Comment by rrd108** [comment]
Perhaps @ManUtopiK if you want to send a PR you are welcome to do it.

Otherwise I need some time to get back to this.

**Comment by rrd108** [comment]
Included in #63

**Comment by rrd108** [comment]
Changing the values of the rules like number of lines is not planned.

However if more users think the rule is too strict we can change the value.

**Comment by David-Pena** [comment]
I'll closed this issue as it's duplicated. Check out progress in #63
