### ISSUE TITLE
rename `order` flag to `sort`

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#173]
Can we rename the `order` flag to `sort`

I added the `output` flag and I want to use the `-o` alias for that what is taken now by the `order` flag.

If yes, we should rename the corresponding types from `orderBy` to `sortBy`

**Comment by David-Pena** [comment]
Yes we can change it, because you are working on something affected by this, I can commit kind of quickly, or you want to add the `good first issue` for this?

**Comment by rrd108** [comment]
Let's try to have the good first issue label and see if somebody jumps in
