### ISSUE TITLE
function size rule output wrong function name and length and does not show line number for the function

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#174]
**Describe the bug**
When I run the analyzer on vue-mess-detector the output shows questions as the function name instead of createFiles, and shows no line number.

**To Reproduce**
run `yarn analyze src/generator/createRule.js -l=error`

1. What is the exact code you are analyzing?
`src/generator/createRule.js`

3. What is the output you are getting?
- rrd ~ function size
   File: src/generator/createRule.js
   Description: 👉 Functions must be shorter than 20 lines. See: https://vue-mess-detector.webmania.cc/rules/rrd/function-size.html
   Message: function (questions) is too long 🚨

**Expected behavior**
Message should be function (createFiles) in line 19 is too long 

**Used version number of vue-mess-detector:**
0.38.0

**Comment by rrd108** [comment]
@David-Pena I added a failing test, I hope it helps. As it was your code can you take this issue?

**Comment by David-Pena** [comment]
Absolutely :( @rrd108, the fourth time is the one 👀

**Comment by rrd108** [comment]
4th time?

Do you beleive in the tale of a ready software? 🤪

**Comment by David-Pena** [comment]
Almost done here... I'm doing a little refactor to the regular function part because its counting the open and close curly braces as part of the body

The fix for the bug indicated in this issue is passing tests and example provided
![image](https://github.com/user-attachments/assets/2390fafb-7372-4d23-a2a6-bdab6bf37e99)

**Comment by David-Pena** [comment]
Added line number 
![image](https://github.com/user-attachments/assets/be09ebdd-e696-429f-ae16-0e9921846eea)

**Comment by David-Pena** [comment]
I created a PR for this #183

**Comment by rrd108** [comment]
Huh that is a really big refactor!

Did you tried to run against the file what was extremely slow with the prevoius version?

**Comment by David-Pena** [comment]
> Did you tried to run against the file what was extremely slow with the prevoius version?

Actually I didnt, let me try

**Comment by David-Pena** [comment]
Was it this one? @rrd108 
![image](https://github.com/user-attachments/assets/0839f8b4-265f-4b90-b85e-0724f5b906b1)

**Comment by rrd108** [comment]
Yes. That is the one

**Comment by David-Pena** [comment]
I run it agains that one:
![image](https://github.com/user-attachments/assets/c3d137b1-bdc1-4b0d-b74b-3acd5e5f7897)
All tests 0.32s ✅

And also against one of my "big" projects
![image](https://github.com/user-attachments/assets/f11b0c41-40f1-4f0a-a9c3-2eacc1d4b721)
All tests 3.8s ✅

**Comment by rrd108** [comment]
Sure. 

Go to sleep. I will do it later
