### ISSUE TITLE
Refactor rename `createMarkdown` to `createDoc`

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#177]
`createMarkdown.js` to `createDoc.js` and corresponding `package.json` script and doc examples

**Comment by AlexVCS** [comment]
Hi there, I'd like to work on this issue. Can you assign it to me please?

**Comment by David-Pena** [comment]
Hi @AlexVCS 

Welcome 🚀

And sure, I'll assign it to you, go ahead

**Comment by rrd108** [comment]
Hi @AlexVCS Do not hesitate to let us know if you need some help :smile:
