### ISSUE TITLE
add rule (rrd) avoid side effects in computed

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#179]
```js
const fullName = computed(() => {
  firstName.value = 'Gauranga' // side effect
  return `${firstName.value} ${lastName.value}`
})
```

Computed should not contain any `xyz.value = 123`

The `functionSize` rule has a function to detect the function body of an arrow function, what may be helpful here. If that is the case it should be moved out to helpers/utilities.

**Comment by David-Pena** [comment]
I created a PR for this #225
