### ISSUE TITLE
add rule (rrd) API route without http method

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#186]
Nor in the filename nor in the code

**Comment by David-Pena** [comment]
I don't get this one

**Comment by rrd108** [comment]
It is about Nuxt (Nitro)

https://nuxt.com/docs/guide/directory-structure/server#matching-http-method

The file names should contain the http method for example `users.post.ts` or if not then `users.ts` should check what http method was used. `if (event.node.req.method != 'POST')`
