### ISSUE TITLE
doc add link the Michael's article on props drilling and event frothing

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#188]
https://michaelnthiessen.com/effective-state-management

**Comment by David-Pena** [comment]
I added it in the `Props Drilling` markdown file in this commit https://github.com/rrd108/vue-mess-detector/commit/6c7b3625bd64cb1bf0c416f091447e456e4e1470

![image](https://github.com/user-attachments/assets/74f7f2b6-6c3e-4f3c-9058-6efe57913284)
