### ISSUE TITLE
experimental: research about tools to automate `CHANGELOG` generation

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#194]

**Comment by rrd108** [comment]
As we (mostly) use conventional commits it can be generated - and it is generated for all the releases.

What is the benefit having a dedicated file for this?

**Comment by David-Pena** [comment]
Some docs about best practices and also most OSS have it.

> Following a defined changelog format can help in tracking the changes made in a systematic way, and help contributors to identify notable changes easily

I know all changes are in the release notes but IMO thats not a tab users visit too much. But just having the file there will cause curiosity in users to check it out... Also in the CHANGELOG we can specify more details or verbose explanation. In the current release notes, I notice the structure is to list the commits names only

Maybe this is not necessary, it was mostly a suggestion 😅

**Comment by rrd108** [comment]
I am ok with it, but we should have a way to auto-generate it. Otherwise it just an extra burden. Perhaps it can be changed manually whenever we want.

**Comment by David-Pena** [comment]
Lets have this issue as exploratory first... so I'll assign it to myself to research some tools for this

**Comment by David-Pena** [comment]
Using this tool https://www.npmjs.com/package/conventional-changelog-cli, with a command you can generate the changelog, we can set it to a pre-commit hook or smth.

It will generate this the first time, and update it when there is already a CHANGELOG file
![image](https://github.com/user-attachments/assets/0d102e0d-9f9b-434c-aaa7-73dc4d9bae95)

Only PRs are visible so individual commits must be added manually I think...

**Comment by rrd108** [comment]
hm. That means you and I have to do PR-s also.

No way to add commits?

**Comment by David-Pena** [comment]
> No way to add commits?

I think it can use commits... I'm not sure, the docs are a bit confusing. I'll keep reading

**Comment by David-Pena** [comment]
It doesnt seem to work for individual commits, for now lets not move forward with this issue. It's not that significant for now.
