### ISSUE TITLE
add rule (rrd): function size

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#2]
functions must be shorter than 20 lines

**Comment by David-Pena** [comment]
Hi @rrd108 

I have a question, is there a structure or logic to follow when building `console.log` output?

**Comment by rrd108** [comment]
You can check the output but they follow the same pattern. The only difference is we use red marking if it is considered an error and yellow if it is a warning.

**Comment by David-Pena** [comment]
Hi @rrd108 I created this PR #59 for this issue

**Comment by David-Pena** [comment]
Hi @rrd108 , #59 was merged so lets close this issue to not fill up the issues tab 👨‍💻
