### ISSUE TITLE
test specific rules

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#200]
Would it be useful to add rules targeting test files?

@David-Pena what is your opinion?

**Comment by David-Pena** [comment]
@rrd108 Yes I agree. For all our tests we are using the same structure: 

![image](https://github.com/user-attachments/assets/993c998a-9fd0-4604-9817-5c0b90123dee)

```js
// some script block declaration
// fileName
// check method
// expect (for length)
// expect (for strict equal)
```

I think we can do something with that, or what have you think about this?

**Comment by David-Pena** [comment]
> I ment addig new rules to check what checks the code in test files. There should be best practices and code smells specific for testing

It sounds interesting... lets research about that 

> This is another thing to address 😱

Issue discovering session...

**Comment by rrd108** [comment]
#208 will be the first one
