### ISSUE TITLE
Add a "Suggested Readings" section to the docs

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#204]
The name can be discussed. But its mainly to showcase some good articles about good practices, or what we consider related to this project's goal...

I know some rules have their own articles but this can be more general about vue mess detector too. For example, we could link our articles about `vue-mess-detector`

what do you think? @rrd108

**Comment by rrd108** [comment]
Cool. I like it.

**Comment by David-Pena** [comment]
I created a PR for this #211
