### ISSUE TITLE
`deepIndentation` rule reports the same line multiple times

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#210]
**Describe the bug**
`deepIndentation` rule reports the same file and line multiple times

**To Reproduce**
```
yarn analyze ./src/index.ts  --apply=deepIndentation
```

1. What is the exact code you are analyzing?
vue-mess-detector

2. What is the output you are getting?

-  rrd ~ deep indentation
   ./src/index.ts
   👉 Try to refactor your component to child components, to avoid deep indentations. See: https://vue-mess-detector.webmania.cc/rules/rrd/deep-indentation.html
   line # 121 indentation: 15 🚨

   ./src/index.ts
   👉 Try to refactor your component to child components, to avoid deep indentations. See: https://vue-mess-detector.webmania.cc/rules/rrd/deep-indentation.html
   line # 121 indentation: 15 🚨

   ./src/index.ts
   👉 Try to refactor your component to child components, to avoid deep indentations. See: https://vue-mess-detector.webmania.cc/rules/rrd/deep-indentation.html
   line # 121 indentation: 15 🚨

**Expected behavior**
` ./src/index.ts` line # 121 should be reported onl yones

**Used version number of vue-mess-detector:**
latest-dev

**Comment by rrd108** [comment]
Maybe just the `from` param is missing from get line number?

**Comment by David-Pena** [comment]
I think so, because for the line number we usually send script.content so if not initial index is given, it's always finding the first occurence.

I think that's what's happening

**Comment by David-Pena** [comment]
Have you try any solutions?
