### ISSUE TITLE
Create a vue dev tools plugin

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#212]
https://devtools.vuejs.org/plugins/api

**Comment by David-Pena** [comment]
Is that guide for the new Vue dev tools? (The one inspired by nuxt?

**Comment by rrd108** [comment]
Yes. At least I think it is

**Comment by rrd108** [comment]
I fixed the link

**Comment by rrd108** [comment]
@brenoepics You can check it at https://github.com/rrd108/vue-mess-detector/tree/212-create-a-vue-dev-tools-plugin

These are what I did to manage to make the rollup build. As I said this is new territory for me and I am not sure at all if we even needs rollup here.

- `package.json` 
    - new `build:rollup` script added
    - new packages added for rollup
    - main changed
    - sideEffects added
    - exports added
    - module, unpkg, jsdelivr, types added
    - peerDependencies added
-  `rollup.config.js` added
- top level awaits are replaced with `then`
- `process` replaced with `process?`
- `src/vue-mess-detector-devtools.ts` added - this is the only devtools related file
- `tsconfig.json` changed
- `vite.config` changed

Here you can see all changes: https://github.com/rrd108/vue-mess-detector/compare/212-create-a-vue-dev-tools-plugin?expand=1

I was using cursor to fix all issues, and as it is a new territory for me I have no idea of 80% of this.

**Comment by rrd108** [comment]
New repo created https://github.com/rrd108/vue-mess-detector-vue-devtools

**Comment by David-Pena** [comment]
Is this closed because it's done? Or just to move the issue to its own repo?

**Comment by rrd108** [comment]
It is closed here because a dedicated repo is created for it
