### ISSUE TITLE
add rule (rrd) use css repeated values

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#215]
We can detect if some values can be extracted to variables.
For example if in the codebase we have multiple `padding: 1em` it can be extracted out

**Comment by David-Pena** [comment]
Okay I'm getting back to this, through the day I'll left here an approach to not destroy the code health of projects because of this rule 👀 @rrd108

**Comment by rrd108** [comment]
I am curious 👀

**Comment by David-Pena** [comment]
> I am curious 👀

Do not get your hopes so up

**Comment by rrd108** [comment]
Will you send a PR?

**Comment by David-Pena** [comment]
Oh today I won't be on so if you can do it, go ahead! 🙌🏻

**Comment by David-Pena** [comment]
@rrd108  https://github.com/rrd108/vue-mess-detector/pull/424
