### ISSUE TITLE
add rule (vue-strong): Component in separate files

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#22]
https://vuejs.org/style-guide/rules-strongly-recommended.html#component-files

**Comment by David-Pena** [comment]
Would this rule be just to check for the pattern .component('...', { ... } inside the file right? Or am I missing something?

**Comment by rrd108** [comment]
Yes, that would be the easiest approach. Perhaps all vue files should be checked.

**Comment by David-Pena** [comment]
Wouldnt the check apply to all files in the given path? or this pattern should just be check in the entry-point file where you can register components globally?

**Comment by rrd108** [comment]
People can do weird things. So I would suggest check all files.

However checking only main.js/ts will be much quicker. But even in a big project it will save less then a second.

What do you think?

**Comment by David-Pena** [comment]
I think checking all files in the given path would be better to avoid missing some really weird component registration (I haven't seen one but there must exists somewhere haha)

However, I'm wondering how you get to that less than a second estimate? If it's that way then I agree it won't be noticeable for the end user

**Comment by rrd108** [comment]
> However, I'm wondering how you get to that less than a second estimate? If it's that way then I agree it won't be noticeable for the end user

All our current checks go throught all the files again and again. 
I have a middle size project and still it runs quickly.

**Comment by David-Pena** [comment]
Got it! Then I support the "check all Vue files" approach for this rule 🤚🏻

**Comment by David-Pena** [comment]
Hi @rrd108 I created a PR for this issue #68
