### ISSUE TITLE
``yarn docs:generate`` creates file with camelCase name instead of kebab-case 

### ISSUE THREAD

**Issue by Whomy09** [rrd108/vue-mess-detector#223]
**Describe the bug**
``yarn docs:generate`` creates file with camelCase name instead of kebab-case 

**To Reproduce**
``yarn docs:generate``

1. What is the exact code you are analyzing?

2. What is the output you are getting?
The markdown file is created using a camelCase name

**Expected behavior**
It should use kebab case

**Screenshots**
![image](https://github.com/user-attachments/assets/b64fd896-191c-4b93-b486-d67eaedc8854)

**Used version number of vue-mess-detector:** 
0.42.0

**Used version number of node & yarn:**
Node: 20.11.0
Yarn: 1.22.22

**Comment by David-Pena** [comment]
This only happens when an in progress rule is selected  (because the `name` arg is the ruleName)
![image](https://github.com/user-attachments/assets/c739bc5d-1eac-4322-8934-5d133259865d)

**Comment by rrd108** [comment]
Ah, that is the result of my prevoius tweaks.

I will fix it soon
