### ISSUE TITLE
add rule (vue-strong): Order of words in component names

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#26]
https://vuejs.org/style-guide/rules-strongly-recommended.html#order-of-words-in-component-names

**Comment by rrd108** [comment]
can we make a rule for this?

**Comment by David-Pena** [comment]
I'd say no because it really depends a lot on each individual project or use case. Rn I can't think of away to assume the correct order of the words (at least not a easy or clear path)
