### ISSUE TITLE
add support for wildcards for `--exclude`

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#265]
For example we have `rule.ts` and `rule.test.ts` files in the same directory.

With this change we can run `yarn analyze --exclude=*test.ts` and all files what match the pattern could be excluded.

**Comment by David-Pena** [comment]
```js
it('should execute with exclude wildcard for test files', async () => {
    const { stdout } = await execa('yarn', ['analyze', '--exclude=*.test.ts'])
    expect(stdout).toContain('Excluding *.test.ts')
})
 ```
 
 
 🚀 ![image](https://github.com/user-attachments/assets/2d6752b5-61ad-4c0a-83d1-1b7303f90631)

**Comment by David-Pena** [comment]
![image](https://github.com/user-attachments/assets/0f017e72-ed0f-4321-9be4-77ac52f715ce)

good enough for another PR

**Comment by rrd108** [comment]
You rock today 🎉

**Comment by David-Pena** [comment]
I created a PR for this @rrd108
