### ISSUE TITLE
Add rule rrd amount of comments 

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#273]
We should check how much comments we have in a file and if it too much (without jsdocs) we should fire a warning 

Any number we decide will be debatablee. My suggestion is more than 5%

**Comment by David-Pena** [comment]
If more than 5% of the total lines are comments, trigger a warning? @rrd108

**Comment by rrd108** [comment]
Yep.

Or reather character count as comments can be in the same line as the code.

What do you think?

**Comment by David-Pena** [comment]
> Or reather character count as comments can be in the same line as the code.

In that case would 5% be a good number? should it be higher or lower?

**Comment by rrd108** [comment]
Let's try with this and check a few files and then we can discuss

**Comment by rrd108** [comment]
jsdoc comments should be ignored

**Comment by David-Pena** [comment]
I want to keep helping with bugs so Ill unasign myself from this

**Comment by David-Pena** [comment]
I created  a PR for this #377
