### ISSUE TITLE
add new overrides

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#283]
- [X] templateSimpleExpression.ts / MAX_EXPRESSION_LENGTH in https://github.com/rrd108/vue-mess-detector/commit/60f573815b3cc777c3c2b2d5e5ca8aa29006ee9c
- [X] simpleComputed.ts / MAX_COMPUTED_LENGTH https://github.com/rrd108/vue-mess-detector/commit/f4652a21de35115a00992bb9394b13a46ef122f9
- [X] fullWordComponentName.ts / MINIMAL_CONSONANTS https://github.com/rrd108/vue-mess-detector/commit/b9505260f5cf2f3aa4431bed9369de3f8ad33530
- [X] tooManyProps.ts / TOO_MANY_PROPS https://github.com/rrd108/vue-mess-detector/commit/8c744aa92b434dc72fdafdac2b11a1a469f3a65c
- [X] shortVariableName.ts / MIN_VARIABLE_NAME https://github.com/rrd108/vue-mess-detector/commit/0f5333ecf1e2de0617e5333eec08c5e0bb88209c
- [X] parameterCount.ts / MAX_PARAMETER_COUNT https://github.com/rrd108/vue-mess-detector/commit/71b061fd85d01eee6828c35a6d86865816e319cd
- [X] deepIndentation.ts / MAX_TABS https://github.com/rrd108/vue-mess-detector/commit/fa5fc014f9ebfa083831e266b4fde9d85c2223c8
- [X] bigVshow.ts / MAX_VSHOW_LINES https://github.com/rrd108/vue-mess-detector/commit/d41cea955ef726ac1217cd1dad784cdf967b3c72
- [X] bigVif.ts / MAX_VIF_LINES https://github.com/rrd108/vue-mess-detector/commit/19fcf63364974e9ca5a713137b18587e4367cfc2
- [X] cyclomaticComplexity.ts / COMPLEXITY_MODERATE https://github.com/rrd108/vue-mess-detector/commit/6ff13b68b7e0732e18bcf5a91d3f0314795fffcd
- [X] complicatedConditions.ts / WARNING_THRESHOLD https://github.com/rrd108/vue-mess-detector/commit/beccd62b33ef167c9bf8835131b3ed13211281f6
- [X] hugeFiles / WARNING_TOTAL_COUNT_THRESHOLD https://github.com/rrd108/vue-mess-detector/commit/f30d003ab4b140eeff2c69a39fefe5f3feea2aab

**Comment by David-Pena** [comment]
Half way there 🙏

**Comment by David-Pena** [comment]
Done 🚀 @rrd108

**Comment by rrd108** [comment]
This is a big step!
Thank you
