### ISSUE TITLE
False positive for nested ternary

### ISSUE THREAD

**Issue by crystalfp** [rrd108/vue-mess-detector#298]
**Describe the bug**
If the statement contains multiple question marks, that is, for "?." and ternary, it is marked as nested ternary (see example below).

**To Reproduce**

1. What is the exact code you are analyzing (this is line 55)?
```
const countDatasets = this.structure?.volume ? this.structure.volume.length : 0;
```
2. What is the output you are getting?
```
-  rrd ~ nested Ternary
   src\electron\nodes\DrawOrthoslice.ts
   👉 Break the nested ternary into standalone ternaries, if statements, && operators, or a dedicated function. See: https://vue-mess-detector.webmania.cc/rules/rrd/nested-ternary.html
   line #55 has nested ternary 🚨
```

**Expected behavior**
Ignore "?." constructs.

**Screenshots**

**Used version number of vue-mess-detector:** 0.6.0

**Used version number of node & yarn:** v22.5.1 and npm, not yarn 10.8.3

**Additional context**

**Comment by David-Pena** [comment]
Thanks for using our tool 🙏🏻

This will probably get fixed by rrd when is on again, if not tomorrow morning I can check it out 🙌🏻

**Comment by rrd108** [comment]
@crystalfp do you want to send a PR for this?

Thanks for reporting 🌟

**Comment by David-Pena** [comment]
I think I solved this

**Comment by David-Pena** [comment]
Its fixed in latest commit https://github.com/rrd108/vue-mess-detector/commit/1e8133bed69eb543e31b6723ea794ba7b26511a4

You can try it out thanks to pkg.pr.new `npm i https://pkg.pr.new/rrd108/vue-mess-detector@1e8133b` @

**Comment by David-Pena** [comment]
@rrd108  is this released already?

I wonder if the issue should be closed after its released or when the fix is done?

**Comment by rrd108** [comment]
I close them when the fix is commited.
And I add a new comment when the fix is released - if I do not forget it

**Comment by rrd108** [comment]
implemented in0.54.0
