### ISSUE TITLE
`exclude` does not skip files with wildcard pattern

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#307]
```bash
yarn analyze --exclude=*.test.ts  
```

Output contains all the `test.ts` files for all rules.

**Comment by David-Pena** [comment]
![image](https://github.com/user-attachments/assets/90853554-d8c6-4649-9f83-3b256fb219d1)
No tests at sight...

**Comment by David-Pena** [comment]
I changed twice some things and it didnt work... I forgot to build before running the tests...

**Comment by David-Pena** [comment]
Fixed in latest commit https://github.com/rrd108/vue-mess-detector/commit/fbb4480cf6841c831581665ee3eedc13527b1af9

It can be check out thanks to pkg.pr.new via `npm i https://pkg.pr.new/rrd108/vue-mess-detector@fbb4480`
