### ISSUE TITLE
skip `app.vue` for name rules

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#318]
In nuxt this is the default component but no fires

- [X] single name component https://github.com/rrd108/vue-mess-detector/commit/cae85244e8a8a4275a437804e68ebc38c13ec9cc
- [X] component name is not PascalCase and not kebab-case https://github.com/rrd108/vue-mess-detector/commit/9f7c0423154ac46d91829feb8dd828f1ecc01ad6
- [X] full-word component names https://github.com/rrd108/vue-mess-detector/commit/e533e3486983a6869b8e97d454ee67f018e017a7

**Comment by David-Pena** [comment]
Done my friend @rrd108
