### ISSUE TITLE
Layouts folder should be skipped for single name component check 

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#345]
Like we do for pages

**Comment by bchanez** [comment]
can i give it a try ?

**Comment by rrd108** [comment]
Sure. Check the current rule.

I think we already has some exception for `layouts`. I can not check it now but you can do a quick search.

Let us know if you need help.

**Comment by David-Pena** [comment]
Nice to have you onboard @bchanez 👀
