### ISSUE TITLE
tsx results in the warning of rule "noTsLang"

### ISSUE THREAD

**Issue by zymbth** [rrd108/vue-mess-detector#362]
**Describe the bug**
`lang=tsx` results in the warning of rule "noTsLang"

**To Reproduce**

1. What is the exact code you are analyzing?

`<script setup lang="tsx">`

2. What is the output you are getting?

```text
-  rrd ~ no ts lang
   src\xxx.vue
   👉 Use typescript instead of javascript. See: https://vue-mess-detector.webmania.cc/rules/rrd/no-ts-lang.html
   component uses js instead of ts 🚨
```

**Expected behavior**
`tsx` should avoid triggering `noTsLang` warning.

**Used version number of vue-mess-detector:** `0.57.0`

**Used version number of node & yarn:** `node@18.20.4`, `pnpm@9.8.0`

**Comment by David-Pena** [comment]
Fixed in last commit, you can try it out before release via `npm i https://pkg.pr.new/rrd108/vue-mess-detector@f468690`
