### ISSUE TITLE
The ts optional symbol sometimes triggers the "nestedTernary"

### ISSUE THREAD

**Issue by zymbth** [rrd108/vue-mess-detector#366]
**Describe the bug**
The ts optional symbol sometimes triggers the detection of rule "rrd ~ nested Ternary"

**To Reproduce**

1. What is the exact code you are analyzing?

```ts
type TestType = { value?: number; name?: string }

const temp: Array<{ value?: number; name?: string }> = []
```

2. What is the output you are getting?

```text
-  rrd ~ nested Ternary
   src\views\Test\ts-nested-ternary.ts
   👉 Break the nested ternary into standalone ternaries, if statements, && operators, or a dedicated function. See: https://vue-mess-detector.webmania.cc/rules/rrd/nested-ternary.html
   line #1 has nested ternary 🚨

   src\views\Test\ts-nested-ternary.ts
   👉 Break the nested ternary into standalone ternaries, if statements, && operators, or a dedicated function. See: https://vue-mess-detector.webmania.cc/rules/rrd/nested-ternary.html
   line #3 has nested ternary 🚨
```

**Expected behavior**
ts optional symbol should avoid triggering the `nestedTernary` detection. 

**Used version number of vue-mess-detector:** `0.57.0`

**Used version number of node & yarn:** `node@18.20.4`, `pnpm@9.8.0`

**Comment by rrd108** [comment]
Thanks for reporting.

Do you want to send a PR?

**Comment by David-Pena** [comment]
Failing test added for reference in last commit

**Comment by David-Pena** [comment]
This is fixed in lastest commit, you can try it out via `npm i https://pkg.pr.new/rrd108/vue-mess-detector@efad70c`
