### ISSUE TITLE
add rule (vue-recommended): Element attribute order

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#39]
https://vuejs.org/style-guide/rules-recommended.html#element-attribute-order

**Comment by David-Pena** [comment]
Hi @rrd108 should we check for non recommended combination of attributes? like `v-if` and `v-for` in the same element? or its not included in the scope of this rule? and can that be another rule?

**Comment by rrd108** [comment]
`v-if` with `v-for` is already implemented (https://github.com/rrd108/vue-mess-detector/blob/main/src/rules/vue-essential/vifWithVfor.ts), as it is one of the `vue-essential` ruleset

**Comment by David-Pena** [comment]
I created a PR for this #92
