### ISSUE TITLE
Incorrectly detecting "No Skipped Tests"

### ISSUE THREAD

**Issue by jonathan-terrell** [rrd108/vue-mess-detector#395]
**Describe the bug**
Incorrectly detecting the skip in the second line of the function. This is not a test, but a function call to a third party security library.

**To Reproduce**
Run analyse on the following code:
const navigateSkip = async () => {
    const state = getAuthFlow().getState<'onboarding_username'>();
    const nextState = await state!.actions.skip(null).run();
    getAuthFlow().handlers[nextState.name](nextState as any);
};

You will receive this message:
 👉 Skipped or todo tests were found. These should be addressed before merging. See: https://vue-mess-detector.webmania.cc/rules/rrd/no-skipped-tests.html
   line #17 skip test found: ".skip" 🚨

**Expected behavior**
Did not expect this message.

**Screenshots**

**Used version number of vue-mess-detector:**
0.62.1

**Used version number of node & yarn:**
Node: v20.15.0

**Additional context**

**Comment by David-Pena** [comment]
Fixed in latest commit, you can try it out via `npm i https://pkg.pr.new/rrd108/vue-mess-detector@201753b` 🫡
