### ISSUE TITLE
Add a bot to post issues from github to the discord server

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#402]
I'd like to create follow this steps: https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22 but I don't have access to it.

Could you help me out? @rrd108 

I'd like to check if with this option `let me select individual events` enables some kind of options to choose "Issue creation" or something like that to trigger this webhook.
![image](https://github.com/user-attachments/assets/3478853f-9f6d-4804-a11d-e7144ceb6677)

I shared the webhook link via discord dm

**Comment by rrd108** [comment]
![Uploading Képernyőkép 2024-10-12 19-11-42.png…]()

**Comment by rrd108** [comment]
![Képernyőkép 2024-03-08 21-38-26](https://github.com/user-attachments/assets/6eba8f45-ffe7-413f-9597-ba55f5c103de)

**Comment by rrd108** [comment]
![Képernyőkép 2024-10-12 19-11-42](https://github.com/user-attachments/assets/4ba58ae4-c3a1-4a3b-be96-1b7ef507d42e)
