### ISSUE TITLE
add rule (vue-caution): Element selectors with scoped

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#42]
https://vuejs.org/style-guide/rules-use-with-caution.html#element-selectors-with-scoped

**Comment by David-Pena** [comment]
@rrd108 I can think of two ways to achieve this:
1.  Check for a pattern like `string { }` inside `<style>` // i.e button { }, Im not completely sure this will handle all cases.
2.  Extract the `<style>` content (all selectors using the above pattern) i.e ['button'] and then check that the matched selector is not included in a list like this https://github.com/sindresorhus/html-tags

What do you think?

**Comment by rrd108** [comment]
First I want to be sure that we are agree on what si this rule.

My understanding is element selectors are ok, but *"large numbers of element selectors are slow"*.

I use element selectors a lot.

I saw some benchmark quite a few months back and the difference between class and element selectors showed after 10,000 html elements on the page.

I guess this is the reason of this rule got into the `vue-caution` group.

So it would be nice to see an up to date banchmark for this and then decide how to apply the rule.

Otherwise I think we have another rule where we would need the list of all html tags. The one you suggested is a very minimal dependency - so it can be added if we really needs it.

**Comment by David-Pena** [comment]
I created a benchmark for this https://github.com/David-Pena/element-class-selector-benchmark/tree/main, check it out and let me know if thats a valid benchmark to decide about this issue

**Comment by rrd108** [comment]
So according to your benchmark with 10,000 html elements the difference is 1ms?

**Comment by David-Pena** [comment]
Oh no, the image showcase was an example. I ran the benchmark multiple times with 10.000 elements up to 50.000 and the results were always `element selectors` being slower than `class selectors`. The difference was most of the time around 8 to 12 ms

I'll update the example in the README to not confuse people

**Comment by rrd108** [comment]
:laughing: 8-12 ms is still a very small number

Anyway we have what we wanted so go ahead with this. But I reccomend make this a warning and not an error and add these numbers to the rule's docs

**Comment by David-Pena** [comment]
From the official docs:
> Element selectors should be avoided with scoped.

I'll omit ⬆️ because the `globalStyle` rule takes care of that right

**Comment by David-Pena** [comment]
I created a PR for this #102
