### ISSUE TITLE
add rule (vue-caution): Implicit parent-child communication

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#43]
https://vuejs.org/style-guide/rules-use-with-caution.html#implicit-parent-child-communication

**Comment by David-Pena** [comment]
For this rule would be enough to check for props mutation (prop inside v-model) and check no $parent, getCurrentInstance are present in the file? 🤔

**Comment by rrd108** [comment]
Yes, it will cover most of the problematic parts.

**Comment by David-Pena** [comment]
Hi @rrd108 I created a PR for this issue #67
