### ISSUE TITLE
Rule "Rename the component to use PascalCase or kebab-case file name" Incorrectly Applied to Pages and Layouts

### ISSUE THREAD

**Issue by bchanez** [rrd108/vue-mess-detector#46]
**Describe the bug**
The rule "Rename the component to use PascalCase or kebab-case file name" is triggered on pages and layout files, whereas it should only apply to component files.

**To Reproduce**

1. What is the exact code you are analyzing?
- src/app.vue
- src/layouts/default.vue
- src/layouts/loginLayout.vue
- src/pages/login.vue

2. What is the output you are getting?
`component name is not PascalCase and not kebab-abse`

**Expected behavior**
The rule "Rename the component to use PascalCase or kebab-case file name" should only apply to component files and not to pages or layout files.

**used version number of vue-mess-detector:**
0.15.0

**Comment by rrd108** [comment]
Yep. I can confirm this rule does not exclude pages and layouts.

Do you want to send a PR for a fix or a failing test?
