### ISSUE TITLE
doc release action fails

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#463]
see: https://github.com/rrd108/vue-mess-detector/actions/runs/11953832934/job/33323294488

**Comment by pieterocp** [comment]
Looks like one of the dependencies has dropped support for node 18 (https://github.com/isaacs/minimatch/commit/632e0da294b644ce2b537df4d64d4316fd84e0f1), so either time to pin it down or bump up the node version runner. (same for other actions erroring, e.g. [Jsr Runner 0.65.0](https://github.com/rrd108/vue-mess-detector/actions/runs/11953940738/job/33322916367) 
```
error minimatch@10.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.20.5"
error Found incompatible module.
```

**Comment by David-Pena** [comment]
How do we approach this? @rrd108 

Case A) Downgrade `minimatch` to a version that still supports `node: 18` 
Case B) Increase engine `node` to 20

**Comment by rrd108** [comment]
As node 22 is active and 20 is maitnenace LTS I think we can bump up to node 20

**Comment by David-Pena** [comment]
@pieterocp would you like to contribute with the bump to node 20?
