### ISSUE TITLE
problematic files report

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#5]
when a file apperas in more reports we should mark them as problematic and at the end list top 5/10

**Comment by David-Pena** [comment]
Hi, I'd like to give it a try to this issue but I don't get this part "and at the end list top 5/10". Could you elaborate more on it please? 🧑🏼‍💻

**Comment by rrd108** [comment]
Currently the report is grouped by **rule**.

The idea with this is grouping by **file**.

So in the current report a file can be reported for multiple rules and it is not as convininet in cases when somebody wants to clear the code file by file and not rule by rule. This implementation would give an output listing problematic files and all offended rules in the particular file.

The last part wanted to say to list only the top 5 or 10 problematic file, but now I think it would be nicer to list all.

Ordering the files is a question, 
 - order the files by starting the most problematic (with the most rules offended).
 - order them as the checks runs

As a starter we can go with the later, and if we want we can add and `order` option later. If you like the idea we can create a dedicated issue for this, to keep this issue focused.

As we want to keep the current rule based listing we need a new command line parameter like `group` what can defaults to `rule` (current solution), or can be `file` for this new report structure.

**Comment by David-Pena** [comment]
Ohh I get it now!

> The last part wanted to say to list only the top 5 or 10 problematic file, but now I think it would be nicer to list all.

I agree, It would be nicer to list it all.

> As a starter we can go with the later, and if we want we can add and order option later. If you like the idea we can create a dedicated issue for this, to keep this issue focused.

the `order` option would be great to have so yes, let's create a dedicated issue for this to have it on the radar.

**Comment by David-Pena** [comment]
Hi @rrd108 

What do you think of this output layout for the `group by file` report?
![image](https://github.com/user-attachments/assets/4906aae6-57c6-4242-834d-1bd201a8d40e)

**Comment by rrd108** [comment]
looks cool

yellow is a warning level, right?

what is the message for?

**Comment by David-Pena** [comment]
> yellow is a warning level, right?

Yes, the background color depends on the one used in each rule. In this example, those two rules uses `BG_WARN`. But I've been confused about when to use each one... only `BG_ERROR` in vue-strong and vue-essential rules?

> what is the message for?

All rules have a loop and console logs of the final message to the user... in this case `parameterCount` always shows the `functionName` and inside parenthesis the number of parameters it has.

But for the `top-level-element-order` the message was the name of the file... so in that case its not worth it to show the name of the file again (its already at the top). So the `message` depends on each rule.

**Comment by rrd108** [comment]
> > yellow is a warning level, right?
> 
> Yes, the background color depends on the one used in each rule. In this example, those two rules uses `BG_WARN`. But I've been confused about when to use each one... only `BG_ERROR` in vue-strong and vue-essential rules?

I wanted to have 2 levels because soe rules - like script length, or complexity - can have a softer and harder limit. By default I would use warnings.

some explanation should be added to the docs #100 and to the contribtuin guide #101 

> > what is the message for?
> 
> All rules have a loop and console logs of the final message to the user... in this case `parameterCount` always shows the `functionName` and inside parenthesis the number of parameters it has.

Ah ok. I guess we should add some text to the number to make it more clear what is it.

> But for the `top-level-element-order` the message was the name of the file... so in that case its not worth it to show the name of the file again (its already at the top). So the `message` depends on each rule.

Ok. Thanks for the explanation.

**Comment by David-Pena** [comment]
> I wanted to have 2 levels because soe rules - like script length, or complexity - can have a softer and harder limit. By default I would use warnings.

You mean to use warnings in ALL cases by default? and if some rules need to use `BG_ERROR` we will change it.

**Comment by rrd108** [comment]
I mean most of the rules will be warnings.

If it can multiple levels then warnings and errors.

If it is something serious then an error.

Unfortunately I have no objective measures.

**Comment by David-Pena** [comment]
Got it, thanks!

**Comment by rrd108** [comment]
same as #64

**Comment by David-Pena** [comment]
@rrd108 

> the order option would be great to have so yes, let's create a dedicated issue for this to have it on the radar.

We never created an issue for the `order` option right?

**Comment by rrd108** [comment]
No we did not yet

**Comment by David-Pena** [comment]
Okay, I'll create it and assign it to myself 👌 #140
