### ISSUE TITLE
Add cli option to `ignore` and `apply` rulesets/rules

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#63]
### Discussed in https://github.com/rrd108/vue-mess-detector/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **David-Pena** July 18, 2024</sup>
Now that you mentioned adding a `group` flag to the `analyze` command in #5, I was wondering what do you think about a feature to toggle on/off rules? (Being this package kind of opinionated for some rules)

And I picture this like though the `analyze` command too, like with the flag `toggle` it will prompt like a CLI to select wich rules you want to apply to the check or not.

But I have no idea how can that be done, or if its worth it so I'll just let the idea here in discussion 👨‍💻</div>

**Comment by rrd108** [comment]
- [ ] ignore rulesets
- [ ] ignore rules
- [ ] apply rulesets
- [ ] apply rules

**Comment by David-Pena** [comment]
Let me know if you need any help with the pending TODOs 👀

**Comment by rrd108** [comment]
I think I will finish this one. You already assigned yourself to a couple others :smile:

**Comment by David-Pena** [comment]
haha, I got excited! keep going then 👌

**Comment by FauconFan** [comment]
Hey!

Is it possible to specify the rules to apply (or ignore) into a config file also?
This is useful when it comes to sharing the same standards across a team.

cli arguments are good, but keeping them in a config file means consistency!

Ty for this software, this is a good linter :)

We discussed about it here: https://x.com/radharadhya/status/1825913771413426300

**Comment by rrd108** [comment]
new issue added #161

**Comment by David-Pena** [comment]
Let me take this issue @rrd108

**Comment by David-Pena** [comment]
Kind of struggling here rethinking the logic to use the same flags for rulesets and specific rules... 

I'll try something and if it doesnt lead me to anything I'll push changes so you check it out and give me a hint 😅

**Comment by rrd108** [comment]
My idea was this 

`--apply=vue-strong,nestedTernary`

The script make an array of the param and then check the array elements.
If it is a ruleset it adds all rule from the ruleset.
If it is a rule it adds the rule.
So in the end the `apply` array has a list of rules to apply.

**Comment by David-Pena** [comment]
I think I have it @rrd108 , I'll update you through the day

**Comment by David-Pena** [comment]
Hi @FauconFan 

I created a PR for this, soon you will be able to test this feature 🚀
