### ISSUE TITLE
Add Cli option `group` in output

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#64]
Details at #5 

Add a cli option to group results by `rule` or `file`

**Comment by David-Pena** [comment]
@rrd108 we agree we can not work on this feature until #63 is finished right? to avoid steping in each other toes

**Comment by rrd108** [comment]
Yes, you are right.

I can wait with the `rules` implmentation while you are working on this. So go ahead if you like.

**Comment by David-Pena** [comment]
I remember you told me about the `yargs` package for the cli. This `group` option should be a namespaced one right? like the `apply` & `ignore`?

**Comment by rrd108** [comment]
Yes. Like those.

**Comment by David-Pena** [comment]
Hi @rrd108 

I wanted to update you on my progress with this issue. It's definitely gonna involve **breaking changes** because the `report` functions in all rules now won't be in charge of any console log.

Right now I have how would be the `rulesReport.ts` after this changes and the output structure would be like this:

per rule ⬇️
![image](https://github.com/user-attachments/assets/1a877f96-7fab-4710-8103-1e116cf79e48)

per file ⬇️
![image](https://github.com/user-attachments/assets/d473a063-7a97-4562-966f-cb3357560083)

This is how the `report` function would look like for `functionSize` rule ⬇️
![image](https://github.com/user-attachments/assets/ff7043cc-0d83-483f-9afb-7135ac6cac3b)

Some helper functions to handle the data structure in `rulesReport` ⬇️
![image](https://github.com/user-attachments/assets/f8ad84e4-4895-4153-8587-d99e4626bd18)

The output comes from here ⬇️
![image](https://github.com/user-attachments/assets/96c6f554-1aef-4da4-be75-483129f47c45)

**Comment by David-Pena** [comment]
There are a few important things missing:
- [ ] add cli option
- [ ] update output messages from all rules
As you can see in the pictures, there are a few rules where in the `message` field appears the fileName again, this is because for lots of rules the output is like a one liner `${filePath}:${lineNumber} ... ` but with the `group` option the filePath is at the top so it shouldnt appear again (it fills the screen a lot).
Or in other cases, the `message` field will require more information as you noticed in #5 
> Ah ok. I guess we should add some text to the number to make it more clear what is it.
- [ ] update all tests
right now the `report` function in all rules returns the array of the offenses. Not the length as before, so all tests need `expect(reportFunctionSize()).toBe(1);` to become `expect(reportFunctionSize().length).toBe(1);`

I think those are the pending tasks for now, what do you think? @rrd108

**Comment by rrd108** [comment]
David, it seems to be awesome, it will be a significant improvement! :star2: 

However I would not call it a braking change. Users communicate only with the `cli` and there is no breaking behaviour there. Yes the output is very different, but I hardly beleive there is any dependent project what deals with the output. So I think this will not be a new major (1.0) version.

Today I will launch the documentation site and we have to change the output links to our docs links #103 

If you need some help in the missings things above, turn them into a separated issue and assign it to me.

**Comment by David-Pena** [comment]
> David, it seems to be awesome, it will be a significant improvement! 🌟

Great!

> but I hardly beleive there is any dependent project what deals with the output. So I think this will not be a new major (1.0) version.

Thanks for the explanation, it makes more sense.

> If you need some help in the missings things above, turn them into a separated issue and assign it to me.

I think I got it, but I'll let you know 🫡

**Comment by David-Pena** [comment]
I just encountered an issue because the tests expect `expect(mockConsoleLog).toHaveBeenLastCalledWith` but with this new struct there is no immediate log output. Do you have any idea how we can fix/work around this?

**Comment by rrd108** [comment]
As the new approach returns instead of logging the tests should check the return value of the function

**Comment by David-Pena** [comment]
You mean only leave the green part of the test and remove the red ones?
![image](https://github.com/user-attachments/assets/470b6fc5-c3e7-460c-b463-c9fde027c1ac)

**Comment by rrd108** [comment]
You can remove the red ones and add something like expect(reportvfornokey()).tobe({})

Perhaps it will not be an empty object. I am off my computer so I can not give you the exact thing.

**Comment by David-Pena** [comment]
I think I know what you mean. Today is a holiday but before logging off I want to finish updating the output messages to show you. The tests Ill fix them later at night probably

**Comment by David-Pena** [comment]
**Without the --group cli option** ⬇️

![image](https://github.com/user-attachments/assets/4bdf6710-8aea-4d9f-8a36-4fe1e2d01a65)

**With the --group=file cli option** ⬇️

![image](https://github.com/user-attachments/assets/6167c403-b2dc-4d67-a96b-61b47260bcf0)

Output messages updated (plus some color changes)!

What do you guys think? @rrd108 @Whomy09

**Comment by David-Pena** [comment]
Hi @rrd108 

> You can remove the red ones and add something like expect(reportvfornokey()).tobe({})

What do you think about this tests ⬇️
![image](https://github.com/user-attachments/assets/eb269aaa-4e8a-473c-b0f0-c0ac7a44b4d7)

And in cases where multiple offenses of the rule (in this case `props mutation & parent/instance`) ⬇️
![image](https://github.com/user-attachments/assets/efab1c26-502c-4da2-9fd3-79ba861e19c6)


For the latter example, maybe we can adhere for to the previous logic of checking the last ouput, in this case we can check only `expect(reportImplicitParentChildCommunication()).toStrictEqual(offenses[offenses.length - 1])`

Let me know if it makes sense? (I just did it with this rule to verify with you if its okay to move forward)

**Comment by rrd108** [comment]
This would be a proper test

```
const filename = 'props-mutation.vue'
    checkImplicitParentChildCommunication(script, filename)
    expect(reportImplicitParentChildCommunication()).toStrictEqual([{
      description: `👉 ${TEXT_WARN}Avoid implicit parent-child communication to maintain clear and predictable component behavior.${TEXT_RESET} See: https://vuejs.org/style-guide/rules-use-with-caution.html#implicit-parent-child-communication`,
        file: "props-mutation.vue",
        message: `line #7 ${BG_WARN}(todo)${BG_RESET} 🚨`,
        rule: `${TEXT_INFO}vue-caution ~ implicit parent-child communication${TEXT_RESET}`,
      },
    ])
```

**Comment by David-Pena** [comment]
The thing is, in the `check` method for each rule, the files array is a constant in the scope of the rule file, so every call or invoke of the `report` method is stacking the results.

I think I tried to reset the files array right before the `report` returns it's offenses and it didn't work but I'll try again

**Comment by rrd108** [comment]
Yes plase commit your code.

I will take a look. Test should run in isolation, they must not have any effect on other tests.

**Comment by David-Pena** [comment]
> Yes plase commit your code.

I just pushed a commit to the branch https://github.com/rrd108/vue-mess-detector/tree/david/feature/group-report.

The sample tests are in `implicitParentChildCommunication.test.ts`

If you run `yarn tests` everything will fail and the console would be unmanageable so narrow the test in the `package.json` 
![Screenshot 2024-08-08 090203](https://github.com/user-attachments/assets/e58094a1-b0ac-4ae8-83fc-c069e5455977)

> I will take a look. Test should run in isolation, they must not have any effect on other tests.

It always seems weird to me when having to increase the expected result having in mind the previous test result, my bad I didn't raise my hand about it 😔

**Comment by rrd108** [comment]
Heh?

Now I am confused

![Képernyőkép 2024-08-08 18-13-12](https://github.com/user-attachments/assets/10f71732-7519-4756-bd6a-e947cd9f1fc7)

The test passes for me.

BTW you can limit what test to run `yarn test implicitParentChild`

**Comment by rrd108** [comment]
Sorry, I see what you mean.

Without filtering out the other tests the output is crazy.

Ok, I will get back to you if I found some solution. Tomorrow is the earliest.

**Comment by David-Pena** [comment]
> Sorry, I see what you mean.

I was afraid I was losing it haha 😅

> Without filtering out the other tests the output is crazy.

Literally, I spent almost an hour trying to make it work because its not that intuitive the behavior 😔

> Ok, I will get back to you if I found some solution. Tomorrow is the earliest.

Thanks 🤝 I will try to find a solution too, I'll report back if I achieve something.

**Comment by rrd108** [comment]
:smile:

It was easy to fix e94185ee869f95cb8ad0b01289b176bd105d3884

**Comment by David-Pena** [comment]
> It was easy to fix https://github.com/rrd108/vue-mess-detector/commit/e94185ee869f95cb8ad0b01289b176bd105d3884

🤯  You won't believe 

![image](https://github.com/user-attachments/assets/da58e5c3-5fe4-452e-9fd9-299cb8cdd9d3)

_I had everything and nothing at the same time_ 😂

**Comment by David-Pena** [comment]
Thanks for the fix!! 

I'll start migrating the all tests and I think by tonight this whole feature can move on the next stage

**Comment by rrd108** [comment]
Sounds great 🤩
