### ISSUE TITLE
add rule (rrd): component uses js and not ts

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#71]
This should be only warning level and implement only when we have the cli options to filter out rules as this one might be quite controversal.

As I understand nuxt 4 might be defaults to ts, so `<script setup>` will mean ts.

**Comment by David-Pena** [comment]
@rrd108  Isnt this rule covered by the `plainScript` rule?

> As I understand nuxt 4 might be defaults to ts, so <script setup> will mean ts.

According to the issue description, we need to check that <script setup> is being used...

**Comment by David-Pena** [comment]
I created a PR for this @rrd108
