### ISSUE TITLE
create docs site

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#72]
something like [nitro](https://nitro.unjs.io/) or [nuxt content](https://content.nuxt.com/)

**Comment by David-Pena** [comment]
What would be display in the docs site? rules only? or a full "landing page"?

**Comment by rrd108** [comment]
I think like a full documentation site, where we have a landing page as the 2 mentioned above, and a more detailed documentation than we have now in the README.

I mean a little more verbose explanation what the rules try to cover, especially the `rrd` group (and I think we will add a `community` group also)

**Comment by David-Pena** [comment]
Would it be in VitePress right?

**Comment by rrd108** [comment]
I was thinking about nuxt content.

Woud be  VitePress an easier solution?

**Comment by David-Pena** [comment]
I haven't try Nuxt Content so I couldn't say. Let's stay with Nuxt Content unless any other option is  clearly better.

**Comment by David-Pena** [comment]
I was checking Nuxt Content, and I see the styles would be from scratch right? or are there any default theme available? i.e in VitePress ⬇️

With the default theme 
![image](https://github.com/user-attachments/assets/7356c26c-129a-43d6-be9e-7232e2ef4fc2)

You get this page
![image](https://github.com/user-attachments/assets/d8dfffb3-6a0a-4d66-bd8e-4bfa5131389f)

**Comment by rrd108** [comment]
Yes, but there is Nuxt Ui or docus.

As this project is about vue and nuxt I would prefer some nuxt solution.

**Comment by rrd108** [comment]
As I see nitro uses undocs what is a more minimal approach then nuxt content. I think I will give it a try

**Comment by David-Pena** [comment]
It would be nice to have it deployed somewhere as a preview so we all can check it out and give feedback 👀 what do you think?

**Comment by rrd108** [comment]
I think I gona use docus. It is super easy to do, however as I see the project as abonded.

Any way, check out the https://github.com/rrd108/vue-mess-detector/tree/72-create-docs-site branch so you can see how does it look and feel.

Any suggestions are welcome

**Comment by rrd108** [comment]
But if you want I can build and publish it somewhere for testing

**Comment by David-Pena** [comment]
Docus is abandoned?

**Comment by rrd108** [comment]
I just realized that vitepress 1.3 is out and it is active development.

So it seems your first suggestion was the best option.

**Comment by David-Pena** [comment]
> But if you want I can build and publish it somewhere for testing

I'd like this if it doesnt require lot of extra effort, if it does, I'll just check the branch... by the way, shouldn't the docs site be its own repo? or can it be integrated with the current project?

> I just realized that vitepress 1.3 is out and it is active development.

And its a product of the Vue/Nuxt ecosystem so that will cover your first approach of wanting a nuxt solution

**Comment by rrd108** [comment]
Here is the docus version: https://jaccoter.webmania.cc/

I will recreate it with vitepress in the next few days and more verbose descriptions and fix todos

**Comment by David-Pena** [comment]
Awesome! 

Let me know if there is a repo where I can contribute 🫡 happy to help

**Comment by rrd108** [comment]
> Let me know if there is a repo where I can contribute 🫡 happy to help

As I want to keep the docs sync in the actual features, and this is a minimal documentation site I think it fits to this repo. We already have a dedicated repo for the vscode extension, I do not see the benefit having another one for the documentation.

So the docs will go into the `docs` folder in this repo.

I added Vitepress to rrd108:72-create-docs-site branch, and moved the docus version to `_docs`. 

You are very welcome to tweak it :smile:

**Comment by rrd108** [comment]
jaccoter.webmania.cc is updated with vitepress

**Comment by rrd108** [comment]
Since you have access you do not have to fork anymore. You can clone it, work on it and push to it.

Just try to keep the main branch clean.

**Comment by David-Pena** [comment]
Ohh you are right! thanks

**Comment by David-Pena** [comment]
Some typos and UI improvements in #84

**Comment by David-Pena** [comment]
Some typos and UI improvements proposal in #84
