### ISSUE TITLE
add `.vscode/settings` or general linter

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#73]

**Comment by rrd108** [comment]
What about a prettierrc? Or both? Or something else?

I would do something what vuejs itself use but the simplest form.

And I have to add a github action to check code formatting later.

**Comment by David-Pena** [comment]
> I would do something what vuejs itself use but the simplest form.

I don't get this part 🤔

> And I have to add a github action to check code formatting later

Oh, you mean this pr autofix #61 ?

**Comment by rrd108** [comment]
> > I would do something what vuejs itself use but the simplest form.
> 
> I don't get this part 🤔

I mean https://github.com/vuejs/core/blob/main/.prettierrc

> 
> > And I have to add a github action to check code formatting later
> 
> Oh, you mean this pr autofix #61 ?

Yes. At least that is an option.

**Comment by bchanez** [comment]
And what do you think about https://github.com/antfu/eslint-config ?

**Comment by rrd108** [comment]
> And what do you think about https://github.com/antfu/eslint-config ?

Yes, I like this.

**Comment by rrd108** [comment]
@bchanez the only rule I do not like so far is "Top-level functions should be declared with function keywordes" Can we add this as an exception?

**Comment by rrd108** [comment]
@bchanez the only rule I do not like so far is "Top-level functions should be declared with function keywordes" Can we add this as an exception?
