### ISSUE TITLE
Use magic-regexp 

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#74]
We use regex patterns almost in all rules. They could be replaced with [magic-regexp](https://regexp.dev/)

Pros:
- magic-regexp easier to read 
- easier to understand 
- so easier to maintain 
- quite easy to implement for most rules

Cons:
- it adds a new thing to know/learn for contributors

@David-Pena what is your opinion on this?

**Comment by David-Pena** [comment]
I have no problem on learning new things, I might start migrating to that package in the rules I've implemented. Let's go for it!

**Comment by rrd108** [comment]
A few rules use it so you can see examples in the repo also

**Comment by David-Pena** [comment]
Added a PR for one rule update #76
