### ISSUE TITLE
`index.test.ts` failing when using `yarn analyze` command

### ISSUE THREAD

**Issue by David-Pena** [rrd108/vue-mess-detector#91]
**Describe the bug**
`Index.test.ts` tests failed whe running `yarn test`

**To Reproduce**
I think its an issue partly with yarn on my machine...

1. What is the exact code you are analyzing?
`index.test.ts`

2. What is the output you are getting?
When I run `yarn test` ⬇️
![image](https://github.com/user-attachments/assets/46391894-82f6-44fc-888d-bd8ba5f48d9b)
Each rule that failed, opens a VScode tab with the file
![image](https://github.com/user-attachments/assets/8e7489f7-dbd9-4fdb-8972-7043b532bb6f)

**Expected behavior**
All tests should pass

**Used version number of vue-mess-detector:**
`0.25.0` (latest release)

**Node & Yarn versions:**
`node v20.15.0`
`yarn v1.22.21`

**Comment by David-Pena** [comment]
I recognized that file being opened from before when I was trying to run `yarn analyze...` after building and it didnt work. So I tried the same solution than back then: use `npx vue-mess-detector analyze` instead of `yarn analyze`.

![image](https://github.com/user-attachments/assets/c0a8d97f-5a7a-4db6-b9c4-653ecb1a3429)

Now it works...

Im wondering if Im using a wrong or outdated version of yarn that makes that happen

**Comment by David-Pena** [comment]
So I wanted to report this here for two reasons:
- Should I comment those tests while working on a feature? because I dont want to replace `yarn` in the main command because its only happening to me.
- If someone else encounter this error, its good to have a "solution" posted somewhere

@rrd108

**Comment by rrd108** [comment]
I added consola recently. Did you executed yarn install?

The test passes on my laptop and on ci. I suspect it is a windows thing.

**Comment by rrd108** [comment]
I will spin up a windows wm and try to reproduce

**Comment by David-Pena** [comment]
> I added consola recently. Did you executed yarn install?

Yes

> The test passes on my laptop and on ci. I suspect it is a windows thing.

Probably :(

> I will spin up a windows wm and try to reproduce

Thanks, for now I'll just change the command when making changes, but I'll restore it before creating a PR

**Comment by rrd108** [comment]
What is your node and yarn version?

**Comment by David-Pena** [comment]
node v20.15.0
yarn v1.22.21

**Comment by bchanez** [comment]
@David-Pena You can find it here `.github/ISSUE_TEMPLATE/bug_report.md`

**Comment by David-Pena** [comment]
Thanks @bchanez , I just pushed a commit for it

**Comment by rrd108** [comment]
I managed to reproduce this on a windows machine

**Comment by rrd108** [comment]
ERR_UNSUPPORTED_ESM_URL_SCHEME only urls with sheme in file, data and node are supported

**Comment by David-Pena** [comment]
> ERR_UNSUPPORTED_ESM_URL_SCHEME only urls with sheme in file, data and node are supported

I checked that error in some GH issues and the error is because of the path in windows starting with `C:` and something with slashes... the proposed solution was to add `.toString()` but in not sure that will apply to this case 🥲

I'll keep searching..

**Comment by rrd108** [comment]
It was a part of that. I will push the solution please test it

**Comment by David-Pena** [comment]
Absolutely 🫡

**Comment by David-Pena** [comment]
> Thank you for testing it on your windows machine.

Thanks for the effort!!

**Comment by rrd108** [comment]
Daniel, if I am not wrong you added your workaround to the contributors guide.

Can you update that?

**Comment by David-Pena** [comment]
I just did it https://github.com/rrd108/vue-mess-detector/commit/802103f6801f84ab09db6db0d0d425359abc81a6

**Comment by David-Pena** [comment]
oh wait, I forgot this
![image](https://github.com/user-attachments/assets/75424e3b-0cb5-4616-8cc3-226909597796)

**Comment by rrd108** [comment]
The others should stay as those who do not involved in the development will use the npx commands

**Comment by David-Pena** [comment]
Then its done 🤝

**Comment by rrd108** [comment]
Great. 🤩
