### ISSUE TITLE
Doc add list of rules on main ruleset pages

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#93]
Every page in `docs/rules/RULESET` should have a list with the names and links to them is enough. Just to help the navigation

**Comment by David-Pena** [comment]
Will you do this one?

**Comment by rrd108** [comment]
Go ahead if you want. 

Before I start working on something I assign it to myself.

**Comment by David-Pena** [comment]
Got it! I'll add the 'good first issue' label and share it with a friend that wants to start on OSS too

**Comment by rrd108** [comment]
Wonderful 🤩

**Comment by David-Pena** [comment]
Hi @rrd108  just to be sure..

This issue is to add all rules in each specific ruleset page right, i.e here
![image](https://github.com/user-attachments/assets/cce429e1-14c5-4b57-9731-6beb4b2c739c)

Adding the names and brief description like in the README will be enough (knowing each rule has its details page)?

**Comment by rrd108** [comment]
Yes. This is the page.

I think a list with the names and links to them is enough. Just to help the navigation.

**Comment by Whomy09** [comment]
Hi, I would like to try this issue

**Comment by David-Pena** [comment]
I already assigned it to you, go ahead! let us know if you have a question or any trouble running the project 🤝

**Comment by rrd108** [comment]
@Whomy09 What is your plan? I would like to release the docs site on Wednesday late afternoon CET. It would be nice to have them in the first version

**Comment by Whomy09** [comment]
@rrd108 I will be working on this and to send it out tomorrow

**Comment by rrd108** [comment]
Thanks for the update
