### ISSUE TITLE
replace function with regex

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#94]
https://github.com/rrd108/vue-mess-detector/blob/e760f4b815c3bc90bb997c65f0c50bff94b5ebf9/docs/checkMissing.js#L71

@David-Pena can you take a look? You are the regx wizard.

I am pretty sure that my complete function can be replaced by a regex

**Comment by David-Pena** [comment]
I'm checking it out 👨‍💻

Is that a test? or how can I run to know if the regx work?

**Comment by rrd108** [comment]
So it suck out the sidebar array from `./docs/.vitepress/config.ts`

The whole thing checks if we have a rule with no docuemntation (it found 3) or missing from the docs' sidebar.

You can run `yarn docs:missing` to run it. If you break it you wil get errors.

**Comment by rrd108** [comment]
Ah one more thing. The code is quite mesy you can refactor it if you want. It is just a quick and dirty solution.

**Comment by David-Pena** [comment]
I've been trying a bit and the thing is Javascript's Regex does not handle recursion, so there is no like oneliner which will do all the job, there are some packages we can use like [balanced-match](https://www.npmjs.com/package/balanced-match) to match string pairs but the code will result in almost the same as the one you did and yours work too so there is no need to install a package.

However it seems it can be done somehow, I'm checking [Matching Nested Constructs in JavaScript](https://blog.stevenlevithan.com/archives/javascript-match-nested) but the main while loop looks quite similar to yours.

Maybe we can try to refactor the file just to improve readability...

What do you think? @rrd108

**Comment by rrd108** [comment]
Does it help we know that it is only one level deep?

Otherwise if it is not something simple, then I am ok with the current solution.

**Comment by David-Pena** [comment]
I'll give it a try

**Comment by David-Pena** [comment]
Well I tried, but I havent been able to work around the recursion issue even when `sidebar` is only one level deep

`Expected ',' or '}' after property value in JSON at position 95`
`Error parsing sidebar JSON: Unexpected token ']', ..."h-vfor" },]" is not valid JSON`
`{"text": "v-if With v-for","link": "/rules/vue-essential/vif-with-vfor" }, SyntaxError: Unexpected end of JSON input`

**Comment by rrd108** [comment]
No problem David, we are good to go with the current solution. And we did not really run out other issues yet. 🫣
